### ISSUE TITLE
Typescript error when replacing regexp with $1$2

### ISSUE THREAD

**Issue by wikoj1021** [sveltejs/svelte-preprocess#474] opened 2022-02-02 18:01 UTC
**Describe the bug**
When upgraded to preprocess in version 4.10.2 can't use replace with $1$2 in string in version 4.10.1 it works fine. 

**Logs**
src/lib/Test.svelte.injected.ts:6:20 - error TS1351: An identifier or keyword cannot immediately follow a numeric literal.

6 const $$vars$$ = [1$2];
                     ~~

18:58:52 [vite] Internal server error:  [svelte-preprocess] Encountered type error

**To Reproduce**
When component with code below is rendered error will occur.
`<script lang="ts">
	let a ='aaaaaa b'.replace(/(a).*(b)/, '$1$2')
</script>`

**Expected behavior**
To run without error and variable a should be equal to 'ab'

**Comment by dummdidumm** [comment] 2022-02-10 08:37
Duplicate of #466 , fixed with latest release

**Closed by dummdidumm** 2022-02-10 08:37 UTC
