### ISSUE TITLE
Can't use interfaces

### ISSUE THREAD

**Issue by benkeil** [sveltejs/svelte-preprocess#220] opened 2020-08-13 14:39 UTC
**Describe the bug**
Can't use interfaces in .svelte files.

**To Reproduce**
Create a file with a TypeScript interface and import it in a .svelte file.

**Expected behavior**
Should work

**Stacktraces**
```
[!] Error: 'default' is not exported by src/MyInterface.ts, imported by src/App.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
```

**Information about your project:**
- Your browser and the version: newest Safari

- Your operating system: macOS 10.15

- `svelte-preprocess` latest

- Whether your project uses Webpack or Rollup: Rollup

**Comment by kaisermann** [comment] 2020-08-13 14:57
Hey @benkeil 👋  

You need to use the `type` import modifier: `import type { ... } from ...`.

Duplicate of #214 and #206

**Closed by kaisermann** 2020-08-13 14:57 UTC
Labels: invalid

**Comment by benkeil** [comment] 2020-08-13 15:40
Still don't get it to run.

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../../adapters/src/FooImpl.ts (1:12)
1: import type Foo from '@project/core/src/Foo';
               ^
2:
3: export default class FooImpl implements Foo {
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

`App.svelte`

```
<script lang="ts">
  import FooImpl from "@project/adapters/src/FooImpl";
  import type Foo from '@project/core/src/Foo';
  const foo = new FooImpl();
</script>

<main>
  <h1>Hello { foo.getFooBar() }!</h1>
</main>
```

I added an example project at https://github.com/benkeil/svelte-ts-demo.
