### ISSUE TITLE
Way to disable External Resource lookup for script & link tags

### ISSUE THREAD

**Issue by btakita** [sveltejs/svelte-preprocess#226] opened 2020-08-24 22:52 UTC
I'm attempting to add svelte-preprocess to my rollup.config build. I have been using svelte components to dynamically load external script & link tags.

```html
<svelte:head>
  <script src={_versioned('/client/pdfmake.min.js')}></script>
  <script src={_versioned('/client/vfs_fonts.js')}></script>
</svelte:head>
```

When running the build, I get the error:

```
[svelte-preprocess] The file  "/path/to/component/{_versioned('/client/pdfmake.min.js')}" was not found.
[svelte-preprocess] The file  "/path/to/component/{_versioned('/client/vfs_fonts.js')}" was not found.
```

It seems like svelte-preprocess is attempting to look for an External Reference. Is there a way to disable this check for some script & link tags?

I do have a workaround atm...

```html
<svelte:head>
  <script {...{src: _versioned('/client/pdfmake.min.js')}}></script>
  <script {...{src: _versioned('/client/vfs_fonts.js')}}></script>
</svelte:head>
```

**Comment by kaisermann** [comment] 2020-10-05 12:35
Hey @btakita 👋  

Sorry for the delay and thanks for the report! Fixed in `4.4.1` 🥳

**Closed** 2020-10-05 12:35 UTC
Labels: bug

**Comment by plmrry** [comment] 2021-05-18 19:53
hi @kaisermann — would it be possible to disable external files altogether?

I have an SSR component that needs to render a script tag like this:
```
<script src="js/main.js" /></script>
```
I don't want svelte-preprocess to try to import `js/main.js`

**Comment by kaisermann** [comment] 2021-05-18 21:22
Hey @plmrry 👋 currently, there's no straightforward way to disable the external file lookup. Is your `js/main.js` being inserted by the preprocessor? Can you share a minimal repro?

In theory, if `js/main.js` doesn't exist at that (relative) path on build time, the preprocessor wouldn't touch the tag.

**Comment by plmrry** [comment] 2021-05-19 15:31
@kaisermann The problem is, it _does_ exist, but as an unbundled file, but I want to render a script tag that will point to the bundled file. Will try to make a minimal demo when I get the chance...

I can get around it by doing this, just a bit hacky
```
<script src={"js/main.js"}></script>
```
There's also this case (which isn't covered by the previous PR fix):
```
<script src="js/{myFile}.js"></script>
```
