### ISSUE TITLE
Sourcemaps offset

### ISSUE THREAD

**Issue by Maggi64** [sveltejs/svelte-preprocess#286] opened 2020-12-05 16:54 UTC
**Describe the bug**
In my current project and in the example repo below the sourcemaps are offset by a few lines. 
This seems to be related to the style tag:
![image](https://user-images.githubusercontent.com/20517052/101258090-70730780-3720-11eb-9788-ba7b6d73bc67.png)

**To Reproduce**  
- clone repo (https://github.com/Maggi64/sapper-sourcemap-offset)
- `npm run dev`
- look at chrome dev tools

**Expected behavior**
Correctly linked sourcemaps. Otherwise debugging issues becomes quite hard.

**Information about your project:**

- Your browser and the version: (Chrome 87)

- Your operating system: (Windows 10)

- Rollup & svelte-preprocess are updated to the newest versions (see repo package.json)

- All other packages used are also on the newest version 

I hope this is the correct place for this issue. Help and suggestions where that problem exactly comes from are appreciated.

Edit: Even without scss preprocessing this issue still persists. Adjusted example repo.

**Comment by benmccann** [comment] 2020-12-07 17:42
I'm guessing this is a bug in Svelte: https://github.com/sveltejs/svelte/pull/5584#issuecomment-733811305. @milahu I know you had done some investigation into this. Not sure if it's something you'll be able to take a look at, but if so I'd be happy to help review

**Comment by milahu** [comment] 2020-12-07 18:28
thanks for the bug : )

a minimal reproduction is: add this to `app.svelte`
```js
throw new Error('this should be line 10');
```
and then look at the JS console
which traces the exception back to `app.svelte` line 11, for example

triggered by using the `svelte-preprocess` plugin
so either blame `svelte-preprocess` or `svelte`
im adding a test to svelte to find out more ..

@dummdidumm do you know more?
ben said you saw the off-by-one bug too

**Comment by dummdidumm** [comment] 2020-12-07 19:09
No I don't know more, but I think it's inside Svelte because inside language-tools we are able to map the warnings correctly.

**Comment by milahu** [comment] 2020-12-07 20:30
small bug in svelte-preprocess:

the regex for `<template>.*</template>` is too greedy
so the input `<template>T1</template><template>T2</template>`
is wrongly replaced with `T1</template><template>T2`

these work as expected in svelte:
```js
	async function preprocess_tag_content(tag_name: 'style' | 'script', preprocessor: Preprocessor) {
		const get_location = getLocator(source);
		const tag_regex = tag_name === 'style'
			? /<!--[^]*?-->|<style(\s[^]*?)?(?:>([^]*?)<\/style>|\/>)/gi
			: /<!--[^]*?-->|<script(\s[^]*?)?(?:>([^]*?)<\/script>|\/>)/gi;
```

**Comment by milahu** [comment] 2020-12-08 00:02
possible cause:

```xml
<!-- This file is generated by Sapper — do not edit it! -->
```

is added on top of every *.svelte file that is passed to svelte.compile

to debug, i patched `node_modules/svelte/compiler.js` like
```diff
 	function compile(source, options = {}) {

+console.log('compile source >>>>'+source+'<<<<');
```

good night ; )

**Comment by milahu** [comment] 2020-12-08 08:43
new suspect:
in svelte.preprocess, this
```html
<style>
    h2 {
        font-size: 15px;
    }
</style>
```
becomes this
```html
<style>
    h2 {
        font-size: 15px;
    }

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW....4iXX0= */</style>
```
before the `/*#` there should be no newline

backtrace:
```
svelte-preprocess/dist/autoProcess.js
  calls transformer 'globalStyle'

svelte-preprocess/dist/transformers/globalStyle.js
  postcss_1.default(plugins).process(content

postcss/lib/lazy-result.js
  let map = new MapGenerator(str, this.result.root, this.result.opts)
  let data = map.generate()

postcss/lib/map-generator.js
  let eol = '\n'
  if (this.css.includes('\r\n')) eol = '\r\n'
  this.css += eol + '/*# sourceMappingURL=' + content + ' */'
```
so .. blame postcss! https://github.com/postcss/postcss/pull/1486

a quickfix could be made with https://github.com/ds300/patch-package

case closed : )

**Comment by dummdidumm** [comment] 2020-12-08 09:20
This happens for me when I use a TS preprocessor only so that can't be it.

**Comment by milahu** [comment] 2020-12-08 09:27
> so that can't be it

should be the same problem

sourcemaps are injected at end-of-file
seems that consumers expect the `/*# sourceMap...` at start-of-line
so a newline must be added ..
but that change (added line + added columns) is not included in the sourcemap

**Comment by dummdidumm** [comment] 2020-12-08 10:23
I'm not sure that's true. If I throw an error inside the script, that error has the wrong line. If the sourceMap-stuff is added inline, then it's added to the end of the script tag, so it should not affect things before that.

For reference, here is how language-tools does the sourcemapping:

1. Find style/script start/end position
2. Preprocess stuff
3. Find style/script start/end position in transformed file
4. Don't merge source maps in to one, keep them seperate

When an original position is requested, find out if it's inside script/style. 
If yes:
1. Find out if the position relative to the generated fragment. For example if script starts at line 2, the relative position is line-2.
2. Use the sourcemap of the script/style to find the original position
3. Find out the position relative to the whole original file. For example if the original position within the script is at line 2, and the script starts at line 2, it's 2+2.

**Comment by milahu** [comment] 2020-12-08 21:19
fixed the postcss bug in https://github.com/postcss/postcss/pull/1487
and guess what .. it works : D

<img src="https://user-images.githubusercontent.com/12958815/101542308-e4244700-39a2-11eb-8b7c-59ad28c7362e.png" width="460px" />

problem was:
appending of the annotation-comment line `/*# sourceMappingURL=.... */`
was not reflected by the sourcemap
so in the result, only N-minus-one lines were mapped
producing these off-by-one errors

**Comment by Maggi64** [comment] 2020-12-09 01:14
@milahu In some cases lines are not of N-1 lines
![image](https://user-images.githubusercontent.com/20517052/101560753-45a8dd80-39c4-11eb-85ae-b694ca5b5de4.png)

**Comment by milahu** [comment] 2020-12-09 03:05
postcss adds one 'bad' line for every preprocessor
in your case postcss calls globalStyle and scss preprocessors

an easier solution is https://github.com/sveltejs/svelte/pull/5754
to make svelte more fault-tolerant
rather than fix all possible preprocessors

**Comment by Maggi64** [comment] 2021-01-02 22:53
I updated my example repo to the newest version including that sourcemap pr. 
The issue still persist sadly.

**Comment by milahu** [comment] 2021-01-03 09:17
found the problem

the preprocessor returns sourcemap not in `result = { code: '...', map: HERE }`
but 'inlined' into `result.code` = attached as 'magic comment line' at end-of-file
```
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW ... vgICB9XG4iXX0= */
```
this magic comment is currently ignored by svelte, but its parsed by the browser
proof: when i remove the magic-comment-last-line, then i get correct mappings

solution: in svelte, detect if preprocessor added the magic-comment-line at end-of-file,
then remove that line, and parse sourcemap from there

@dmitrage do you wanna fix this?

**Comment by benmccann** [comment] 2021-01-03 13:53
Or should we fix the preprocessor instead to return the map in `code.map`? That seems like it might be the cleaner solution than making Svelte core understand non-standard behavior

**Comment by milahu** [comment] 2021-01-03 14:07
its a de-facto-standard, so id say we make svelte more tolerant. im working on it, the only challenge is parsing multiple attachments, and eventually merging them with `result.map`, which is ambiguous since the time-order of the maps is unclear --> needs a new config in the preprocessor interface

**Comment by dummdidumm** [comment] 2021-01-03 14:55
What do you mean by "multiple attachments" and "time-order is unclear"? The order in which script/style/markup is preprocessed is fixed at the moment.

**Comment by milahu** [comment] 2021-01-03 14:58
a preprocessor can return sourcemaps in `result.map` or in `result.code` or in both. when in both, the order is ambiguous, and we need a new flag like `result.attachedSourcemapIsLast = true | false`. its an edge case, but should be supported

**Comment by milahu** [comment] 2021-01-03 19:04
@Maggi64 can you test my patch in https://github.com/milahu/svelte/tree/parse-attached-sourcemap?

**Comment by dmitrage** [comment] 2021-01-03 22:59
> @dmitrage do you wanna fix this?

@milahu sorry, will be almost off in the next few days.

> now focussing on the simple cases

I'd vote for keeping this direction.

Edge cases with multiple/mixed inline/external maps are rare enough and preprocessor side has more context of how to deal with them. Adding api sugar for such seems excess and increasing maintenance burden.

In contrast, extracting map from single inline comment with no external returned is unambiguous, easy to implement and sounds common.

**Comment by CherryDT** [comment] 2021-01-04 12:53
I'm noticing this also with a `prependData` for my SCSS, it causes errors inside the style blog to appear at the wrong line (probably the line inserted by `prependData` is counted even though it doesn't exist in source):

![image](https://user-images.githubusercontent.com/6010463/103537157-30748100-4e94-11eb-9b88-0726f23e7114.png)

**Comment by Maggi64** [comment] 2021-01-05 11:06
@milahu thanks for helping me out with this issue. 👍 

Tried your branch, it indeed works for the example repo and seemed to fix the sourcemap for most cases.

But when i turn on scss preprocessing it it offset again sadly.

Try this:
![image](https://user-images.githubusercontent.com/20517052/103639238-5c543d00-4f4e-11eb-9601-60de4089325f.png)

**Comment by egargan** [comment] 2021-01-05 13:07
Not sure if this will be coming from the same issue (this discussion seems to revolve around the style block), but sourcemaps for TS script blocks also aren't correct.

Reproducing is as easy as cloning the [template repo](https://github.com/sveltejs/template), running that `scripts/setupTypeScript.js` script, `npm install`, then add a few random lines to the `App.svelte`'s script block. Should be obvious that the lines don't match up.

<details>
<summary>E.g.</summary>

**Non-TS block**

![image](https://user-images.githubusercontent.com/27496517/103649353-36cb3180-4f56-11eb-8937-413f833ca318.png)

**TS block**

![image](https://user-images.githubusercontent.com/27496517/103649255-13a08200-4f56-11eb-9892-090b5f6b5ca0.png)
</details>

**Comment by milahu** [comment] 2021-01-05 14:07
> But when i turn on scss preprocessing it is offset again sadly.

where can i see that?

> sourcemaps for TS script blocks also aren't correct ... Reproducing is as easy as cloning the [template repo](https://github.com/sveltejs/template), running that `scripts/setupTypeScript.js` script ...

when i run `npm run build` i get the warning

> (!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.

looks like a bug in the template config

**Comment by milahu** [comment] 2021-01-05 18:10
aah yes. speculation: scss adds the magic comment without a newline, like

```css
div {
  color: red;
}/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW ... vgICB9XG4iXX0= */
```
todo:
find attached sourcemap without seeking to last newline
simply use a regex? like 
`\/[/*]# sourceMappingURL=data:application\/json;\S*base64,([a-zA-Z0-9+/]+={,2}) ?(?:\*\/)?$`

`\S*` matches `charset=utf-8;` for example

**Comment by milahu** [comment] 2021-01-15 09:09
one problem is: [sourcemap support](https://github.com/sveltejs/rollup-plugin-svelte/commit/7503feb87d91636a69519a0463353f9a864e334e) in rollup-plugin-svelte is [not yet released](https://github.com/sveltejs/rollup-plugin-svelte/issues/175)
workaround: `npm i -D https://github.com/sveltejs/rollup-plugin-svelte.git`

**Comment by milahu** [comment] 2021-01-18 09:03
@Maggi64 @CherryDT @egargan solved?

**Comment by egargan** [comment] 2021-01-18 09:23
Good spot! Installing `rollup-plugin-svelte` directly from GitHub does make a difference, not a good one though. Using the same example from [my last comment](https://github.com/sveltejs/svelte-preprocess/issues/286#issuecomment-754624741), this is what I see now.

![image](https://user-images.githubusercontent.com/27496517/104896125-9f5ed900-596e-11eb-9d70-639daa4375fc.png)

**Comment by milahu** [comment] 2021-01-18 14:01
looks like svelte-preprocess fails to parse the sourcemap from typescript
only start-tag and close-tag are mapped, but not the content

App.svelte
```
src 1: <script lang="ts">
src 2: 
src 3: 
src 4: 
src 5: 
src 6: export let name: string;
src 7: 
src 8: 
src 9: 
src 10: console.log('this is line 10' as string);
src 11: 
src 12: 
src 13: </script>
```
result.code from typescript
```
src 1: <script lang="ts">export let name;
src 2: console.log('this is line 10');
src 3: </script>
```
result.map from typescript
<pre>
1:0 &lt;-- App.svelte 1:0 <span color="red">&lt;</span><span color="#fcfcfc">script lang="ts"&gt;export let name: string;
</span>1:1 &lt;-- App.svelte 1:1 &lt;<span color="red">s</span><span color="#fcfcfc">cript lang="ts"&gt;export let name: string;
</span>1:7 &lt;-- App.svelte 1:7 &lt;script<span color="red"> </span><span color="#fcfcfc">lang="ts"&gt;export let name: string;
</span>1:8 &lt;-- App.svelte 1:8 &lt;script <span color="red">l</span><span color="#fcfcfc">ang="ts"&gt;export let name: string;
</span>1:12 &lt;-- App.svelte 1:12 &lt;script lang<span color="red">=</span><span color="#fcfcfc">"ts"&gt;export let name: string;
</span>1:13 &lt;-- App.svelte 1:13 &lt;script lang=<span color="red">"</span><span color="#fcfcfc">ts"&gt;export let name: string;
</span>1:14 &lt;-- App.svelte 1:14 &lt;script lang="<span color="red">t</span><span color="#fcfcfc">s"&gt;export let name: string;
</span>1:16 &lt;-- App.svelte 1:16 &lt;script lang="ts<span color="red">"</span><span color="#fcfcfc">&gt;export let name: string;
</span>1:17 &lt;-- App.svelte 1:17 &lt;script lang="ts"<span color="red">&gt;</span><span color="#fcfcfc">export let name: string;
</span>3:0 &lt;-- App.svelte 13:0 <span color="red">&lt;</span><span color="#fcfcfc">/script&gt;
</span>3:1 &lt;-- App.svelte 13:1 &lt;<span color="red">/</span><span color="#fcfcfc">script&gt;
</span>3:2 &lt;-- App.svelte 13:2 &lt;/<span color="red">s</span><span color="#fcfcfc">cript&gt;
</span>3:8 &lt;-- App.svelte 13:8 &lt;/script<span color="red">&gt;</span>
</pre>

= line `2 <-- 10` is not mapped, browser shows line 1 in console = uses previous mapping? `1:17 <-- 1:17`

**Comment by Maggi64** [comment] 2021-01-18 15:58
@milahu Thank you very much, works perfectly. I also tested some more complex configs with autoprefixer & sass prependData.
Lines did map correctly.

Would like to see these PRs merged to fix the issue: @benmccann 
- https://github.com/sveltejs/svelte/pull/5854
- https://github.com/sveltejs/rollup-plugin-svelte/issues/175

Related PRs: Bug is fixed without using this PR. Don't exactly know what this is for.
- https://github.com/sveltejs/svelte-preprocess/pull/297

**Comment by Conduitry** [comment] 2021-01-25 23:00
Thanks to https://github.com/sveltejs/svelte/pull/5854, `svelte@3.32.0` will now also look for sourcemaps embedded in preprocessor output.

**Comment by benmccann** [comment] 2021-01-25 23:38
A new version of `rollup-plugin-svelte` has been released as well. Please try updating both `svelte` and  `rollup-plugin-svelte` and seeing if it fixes this for you. I'm not 100% sure it will, but it should at least be closer

**Comment by egargan** [comment] 2021-01-26 11:13
Still facing [the same issues as before](https://github.com/sveltejs/svelte-preprocess/issues/286#issuecomment-762111446), TS <script> blocks' source maps appear to map everything to the first line. Again, I'm just running the template repo, adding a couple of lines to `App.svelte`'s script block and checking whether I can set breakpoints in devtools (I'm not sure how else to verify, don't know much about sourcemaps!).

This is with `svelte@3.32.0`, `rollup-plugin-svelte@7.1.0`, and `svelte-preprocess@4.6.3` - all latest versions.

**Comment by Maggi64** [comment] 2021-01-26 12:07
@benmccann @Conduitry Thanks at least for me all issues are fixed

**Comment by dummdidumm** [comment] 2021-01-26 13:05
> 
> 
> Still facing [the same issues as before](https://github.com/sveltejs/svelte-preprocess/issues/286#issuecomment-762111446), TS <script> blocks' source maps appear to map everything to the first line. Again, I'm just running the template repo, adding a couple of lines to `App.svelte`'s script block and checking whether I can set breakpoints in devtools (I'm not sure how else to verify, don't know much about sourcemaps!).
> 
> This is with `svelte@3.32.0`, `rollup-plugin-svelte@7.1.0`, and `svelte-preprocess@4.6.3` - all latest versions.

I think the problem is #300 - `svelte-preprocess` does not seem to support the `extends`-feature of the `tsconfig.json`, which means that source mapping is off. If you add `"sourceMap": true` to `compilerOptions` you will likely get better results.

**Comment by milahu** [comment] 2021-01-26 13:56
> I think the problem is #300 - svelte-preprocess does not seem to support the extends-feature of the tsconfig.json, which means that source mapping is off.

nope, when `sveltePreprocess({ sourceMap: true })` is called (development mode)
then `opts = { compilerOptions: { sourceMap: true } }` should be set by `getTransformerOptions`
as last step, so other values for `sourceMap` are overwritten

https://github.com/sveltejs/svelte-preprocess/blob/4446571f36dfcf7ac5111deb122bf85c7d92cb6c/src/autoProcess.ts#L129-L133

https://github.com/sveltejs/svelte-preprocess/blob/4446571f36dfcf7ac5111deb122bf85c7d92cb6c/src/modules/language.ts#L39-L41

> TS <script> blocks' source maps appear to map everything to the first line

"map everything to the first line" happens when `svelte-preprocess` returns no sourcemap

\*should\* be fixed by https://github.com/sveltejs/svelte-preprocess/pull/299 = `svelte-preprocess@4.6.2`, but maybe there is another bug in that code

> This is with ... svelte-preprocess@4.6.3 

100% sure? please run

```bash
node -e 'console.log(require("svelte-preprocess/package.json").version)'
```

**Comment by egargan** [comment] 2021-01-26 14:03
> 100% sure? please run...

Yep 100%.

```
svelte/template % node -e 'console.log(require("svelte-preprocess/package.json").version)'
4.6.3
```

Perhaps the config created by the `scripts/setupTypeScript.js` isn't correct? I've hacked around with some combinations of adding/removing 'sourceMap' in various config blocks, no dice. I realise I'm not being very helpful haha, it's just that I'm a bit out of my depth here and I don't have much time to spare to learn what's going on and look into this!

**Comment by kaisermann** [comment] 2021-02-03 19:29
I'm reading the whole thread and I'm a bit lost. Apart from `prependData` modifications not being considered by the sourcemap, are the other issues fixed? 

(the ts sourcemap prop I know it is, thanks @milahu 🎉 )

**Comment by milahu** [comment] 2021-02-03 20:23
should be all fixed, @Maggi64 said

> I also tested some more complex configs with autoprefixer & sass prependData.
> Lines did map correctly.

**Closed** 2021-02-03 23:49 UTC

**Comment by CherryDT** [comment] 2021-02-27 14:10
Hm, but, my issue still exists:

![image](https://user-images.githubusercontent.com/6010463/109389697-bac5e800-790d-11eb-857d-ab507c9080e9.png)

On 4.6.9

**Comment by dummdidumm** [comment] 2021-02-27 15:26
That's the VS Code extension puttung out these warnings, that's unrelated. The VS Code extension uses a somewhat incomplete approach to this and I plan to refactor this some day.
