### ISSUE TITLE
Typescript in component markup

### ISSUE THREAD

**Issue by l1bbcsg** [sveltejs/svelte-preprocess#568] opened 2022-12-21 10:30 UTC
Docs note the following:

> Using TypeScript inside a component's markup is currently not supported. See #318 for development updates to this.

And there's also issue #378 that was closed in favor of the same #318

#318 however is closed as completed via #392, so its original issue resolved, which was not really about transpiling code found with component markup section.

What is the current status of the issue of using TS in templates?

As far as I understand it's still not supported and for this reason it's also not possible to downgrade ECMA versions for bits of code in HTML templates, thus making svelte-preprocess not production-friendly.

**Comment by dummdidumm** [comment] 2023-03-06 09:46
Closing as duplicate of #525

**Closed by dummdidumm** 2023-03-06 09:46 UTC

**Comment by l1bbcsg** [comment] 2023-03-06 10:02
The docs should be updated at least. Currently it leads to a tangled mesh of issues with no clear status.
