### ISSUE TITLE
Transpilation error "Not implemented undefined" when enabling babel

### ISSUE THREAD

**Issue by dritter** [sveltejs/svelte-preprocess#593] opened 2023-04-26 09:32 UTC
Hi there!

I tinkered around with code from https://youtu.be/zVfd4ou9qaw?t=1033 and stumbled upon a compilation error when enabling babel. This code works perfectly fine without babel.

![](https://user-images.githubusercontent.com/1544760/234532243-adc84672-1408-4345-9720-3bc8079526eb.png)

### Reproducer

1. git clone https://github.com/dritter/sveltekit-babel-compile-error-reproducer
2. cd sveltekit-babel-compile-error-reproducer
3. npm i
4. npm run dev -- --open

I copied the code from the video above into Counter.svelte. [This line](https://github.com/dritter/sveltekit-babel-compile-error-reproducer/blob/main/src/routes/Counter.svelte#L12) causes the Bug to surface.

The babel config is from the [README.md](https://github.com/sveltejs/svelte-preprocess#modern-javascript-syntax).

### Stacktraces

<details>
  <summary>Stack trace</summary>
[vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/src/routes/Counter.svelte"
|- Error: Not implemented undefined
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6828:9)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7084:18
    at Array.map (<anonymous>)
    at handle_body (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7083:21)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7168:7
    at scoped_fn (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7052:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7084:18
    at Array.map (<anonymous>)
    at handle_body (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7083:21)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7168:7
    at scoped_fn (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7052:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at LabeledStatement (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7210:53)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7084:18
    at Array.map (<anonymous>)
    at handle_body (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7083:21)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7168:7
    at scoped_fn (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7052:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7649:24
    at scoped_fn (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7052:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:8077:44
    at Array.map (<anonymous>)
    at CallExpression (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:8077:31)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at VariableDeclarator (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7420:52)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7140:3
    at Array.map (<anonymous>)
    at handle_var_declaration (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7139:40)
    at VariableDeclaration (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7415:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7084:18
    at Array.map (<anonymous>)
    at handle_body (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7083:21)
    at Program (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:7162:10)
    at handle (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:6831:17)
    at print (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:8458:17)
    at Component.generate (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:42576:22)
    at compile (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/svelte/compiler.mjs:43792:22)
    at compileSvelte2 (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:573:22)
    at async TransformContext.transform (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:2335:25)
    at async Object.transform (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:42863:30)
    at async loadAndTransform (file:///home/dritter/Projekte/sveltekit-babel-compile-error-reproducer/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:53342:29)
</details>

### Information about your project

  System:
    OS: Linux 6.2 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.70 GB / 15.39 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.9.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 112.0.5615.165
    Firefox: 112.0.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.15.8 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.3.0 => 4.3.2

**Comment by Conduitry** [comment] 2023-04-26 10:49
This is a duplicate of https://github.com/sveltejs/svelte/issues/6706

**Closed** 2023-04-26 10:49 UTC
